#!/bin/zsh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Format everything but only re-add files that were previously on stage.
cargo fmt && (git diff --name-only --cached | xargs git add)